#ifndef ASEMANCLIENTLIB_GLOBAL_H
#define ASEMANCLIENTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASEMANCLIENTLIB_LIBRARY)
#  define ASEMANCLIENTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ASEMANCLIENTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ASEMANCLIENTLIB_GLOBAL_H
